### ISSUE TITLE
Error compiling qtdeclarative-everywhere-src-6.3.0

### ISSUE THREAD

**Issue by kang2k10** [PhysicsX/QTonRaspberryPi#10]
Hello.

/home/owner/qt6rpi/bin/qt-configure-module .
Build files have been written to: /home/owner/qt-cross/qtdeclarative-everywhere-src-6.3.0

but
cmake --build . --parallel 4
[27/2654] Generating .qsb/scenegraph/shaders_ng/24bittextmask.frag.qsb
FAILED: src/quick/.qsb/scenegraph/shaders_ng/24bittextmask.frag.qsb /home/owner/qt-cross/qtdeclarative-everywhere-src-6.3.0/src/quick/.qsb/scenegraph/shaders_ng/24bittextmask.frag.qsb 
cd /home/owner/qt-cross/qtdeclarative-everywhere-src-6.3.0/src/quick && /home/owner/qt6rpi/bin/qsb --glsl 100es,120,150 --hlsl 50 --msl 12 -b -O -s -o /home/owner/qt-cross/qtdeclarative-everywhere-src-6.3.0/src/quick/.qsb/scenegraph/shaders_ng/24bittextmask.frag.qsb /home/owner/qt-cross/qtdeclarative-everywhere-src-6.3.0/src/quick/scenegraph/shaders_ng/24bittextmask.frag
/bin/sh: 1: /home/owner/qt6rpi/bin/qsb: Exec format error
[30/2654] Automatic MOC for target Qml
ninja: build stopped: subcommand failed.
[CMakeError.log](https://github.com/PhysicsX/QTonRaspberryPi/files/8941677/CMakeError.log)

how fix this ?

**Comment by kang2k10** [comment]
i fix.
in manual, has error
`$ cd qtshadertools-everywhere-src-6.3.0
$ /home/ulas/qt6Host/bin/qt-configure-module .
$ cmake --build . --parallel 4
$ **cmake install** `
cmake --install .

**Comment by PhysicsX** [comment]
Hello where is the problem in the manual?
I can see "cmake --install ." Can you point out ?

**Comment by kang2k10** [comment]
![2022-06-20 231558](https://user-images.githubusercontent.com/55108857/174672412-7942271f-0b49-4e4a-baea-ced5454948e5.jpg)

**Comment by PhysicsX** [comment]
Thanks for pointing out. Page is updated.
 
If you watch the video, it will be better to follow the commands step by step to verify also.
But I think you already finished it.

**Comment by kang2k10** [comment]
Yes, in the video, all done.
