### ISSUE TITLE
Can not add the Qmake to the QT Versions whitch in QT Creator

### ISSUE THREAD

**Issue by 1075224835** [PhysicsX/QTonRaspberryPi#11]
Thank You! I finished the  step by step tutorial 。After that，I want to use QT Creator to design the QT project for Rpi4. I need to add QT to QT Versions whitch in QT Creator,I selected ~/qt6rpi/bin/qmake ,it's not working， the raising error is “Qmake Not Executable，The qmake executable /home/yyl/qt6rpi/bin/qmake could not be added.”,I don't know how to fix it. can you help me?

**Comment by PhysicsX** [comment]
Hello

You will not use qmake anymore. Try to configure with cmake. Qt6 uses cmake.
