### ISSUE TITLE
How RPi OS image is constructed

### ISSUE THREAD

**Issue by tongkl1** [PhysicsX/QTonRaspberryPi#16]
First off, kudos for the wonderful work! I'm having a hard time cross-compiling Qt6 and PySide6 for Raspberry Pi 4, so this repo REALLY helps me a lot.

I want to ask how you determine which packages are necessary for the custom built RaspberryPi OS. Did you go through the `packages` files in the official Rpi OS repo and remove unrelated ones, then add the ones required in the Qt official cross-compiling tutorial?

Thank you!

**Comment by PhysicsX** [comment]
Thank you, do not forget to give a star and like/share the video :)

I do not understand the question, you mean in the container ? I just choose bokwoorm which is the type that rasp is using now. For packages, if you ask container, I tried before many times. It is mostly related with experience, I know the packages which are needed for Qt. I am not sure that there is a clear document which shows the dependencies.
