### ISSUE TITLE
cross-compile

### ISSUE THREAD

**Issue by ponnyao** [PhysicsX/QTonRaspberryPi#17]
I sincerely ask God for help. Thank you.I put my jetson orin through rsync and put /usr and /lib into ~/orin/sysroot under wsl ubuntu, and then cross-compile my application, and an error occurred
![image](https://github.com/PhysicsX/QTonRaspberryPi/assets/144422517/cca4a997-8cee-47c8-9262-11c96d9b886d)
......
![image](https://github.com/PhysicsX/QTonRaspberryPi/assets/144422517/6fb15e46-354f-4195-a503-487e89ba4eaa)
......
![image](https://github.com/PhysicsX/QTonRaspberryPi/assets/144422517/331e84a1-e742-4d40-b93c-d2bf8f4012b0)

**Comment by ponnyao** [comment]
> I sincerely ask God for help. Thank you.I put my jetson orin through rsync and put /usr and /lib into ~/orin/sysroot under wsl ubuntu, and then cross-compile my application, and an error occurred ![image](https://private-user-images.githubusercontent.com/144422517/321825281-cca4a997-8cee-47c8-9262-11c96d9b886d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODQ4NjUsIm5iZiI6MTcxMjg4NDU2NSwicGF0aCI6Ii8xNDQ0MjI1MTcvMzIxODI1MjgxLWNjYTRhOTk3LThjZWUtNDdjOC05MjYyLTExYzk2ZDliODg2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwMTE2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDJlODU3ODBmODNkYjM0MWZiNGMzNjYxMjBlMDg1NTYwODViMzMxZDgxMmUyOWRjNjk5NmViODcwYjJlMTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U_-HFY5HUShsCLVdHKx2Xe30chyaBvtq--tBtBrNfjk) ...... ![image](https://private-user-images.githubusercontent.com/144422517/321825444-6fb15e46-354f-4195-a503-487e89ba4eaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODQ4NjUsIm5iZiI6MTcxMjg4NDU2NSwicGF0aCI6Ii8xNDQ0MjI1MTcvMzIxODI1NDQ0LTZmYjE1ZTQ2LTM1NGYtNDE5NS1hNTAzLTQ4N2U4OWJhNGVhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwMTE2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDk2OGUyOTQxYjZmYzFhZjAwOTVhNTE3OGNhZmRhN2M2OGFkNWRlNjg5MWU3MzAwYjg2ODIyMDljZjc3ZjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ANkAYRSvFuGgcOat73tykOn8-iCacPKwWdg_mg43BCc) ...... ![image](https://private-user-images.githubusercontent.com/144422517/321825569-331e84a1-e742-4d40-b93c-d2bf8f4012b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODQ4NjUsIm5iZiI6MTcxMjg4NDU2NSwicGF0aCI6Ii8xNDQ0MjI1MTcvMzIxODI1NTY5LTMzMWU4NGExLWU3NDItNGQ0MC1iOTNjLWQyYmY4ZjQwMTJiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwMTE2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTYwMjhlNWE2MWUwNGNlYmI2YWFjYjM2YzkzODlmMTIzYjI4ZTI2NWVhN2M1ZWY2Y2E0NmMyMTZkNmY3NTRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ovIV3DhNbiVU9TKZnCUr1eMZPXvROtOnqf40czJPlVk)


orinCroosTool.cmake--------------------------------------------------------------------------------------

cmake_minimum_required(VERSION 3.10)
include_guard(GLOBAL)

# Set the system name and processor for cross-compilation
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

# Set the target sysroot and architecture
set(TARGET_SYSROOT /home/yao/orin/sysroot)
set(TARGET_ARCHITECTURE aarch64-linux-gnu)
set(CMAKE_SYSROOT ${TARGET_SYSROOT})

set(CMAKE_FIND_ROOT_PATH ${TARGET_SYSROOT})
set(CMAKE_INCLUDE_PATH ${TARGET_SYSROOT}/usr/include)
set(CMAKE_INCLUDE_PATH ${TARGET_SYSROOT}/usr/include/aarch64-linux-gnu)
set(CMAKE_LIBRARY_PATH ${TARGET_SYSROOT}/usr/lib)


# Add library directories
list(APPEND CMAKE_LIBRARY_PATH "${TARGET_SYSROOT}/usr/lib")
list(APPEND CMAKE_LIBRARY_PATH "${TARGET_SYSROOT}/lib/aarch64-linux-gnu")
list(APPEND CMAKE_LIBRARY_PATH "${TARGET_SYSROOT}/usr/lib/aarch64-linux-gnu")

set(CMAKE_INSTALL_RPATH "${TARGET_SYSROOT}/lib/aarch64-linux-gnu")
list(APPEND CMAKE_RPATH_LINK_PATH "${TARGET_SYSROOT}/lib/aarch64-linux-gnu")

 
# Add RPATH link directories
list(APPEND CMAKE_RPATH_LINK_PATH "${TARGET_SYSROOT}/usr/lib")
list(APPEND CMAKE_RPATH_LINK_PATH "${TARGET_SYSROOT}/usr/lib/aarch64-linux-gnu")
list(APPEND CMAKE_RPATH_LINK_PATH "${TARGET_SYSROOT}/lib/aarch64-linux-gnu")

# Set paths for CUDA libraries
set(CUDA_INCLUDE_DIR ${TARGET_SYSROOT}/usr/local/cuda/include)
set(CUDA_LIB_DIR ${TARGET_SYSROOT}/usr/local/cuda/lib64)

# Configure the pkg-config environment variables
set(ENV{PKG_CONFIG_PATH} "$ENV{PKG_CONFIG_PATH}:${CMAKE_SYSROOT}/usr/lib/${TARGET_ARCHITECTURE}/pkgconfig")
set(ENV{PKG_CONFIG_LIBDIR} "${TARGET_SYSROOT}/usr/lib/pkgconfig:${TARGET_SYSROOT}/usr/share/pkgconfig:${CMAKE_SYSROOT}/usr/lib/${TARGET_ARCHITECTURE}/pkgconfig:${CMAKE_SYSROOT}/usr/lib/pkgconfig")
set(ENV{PKG_CONFIG_SYSROOT_DIR} "${CMAKE_SYSROOT}")

# Set the C and C++ compilers
set(tools /home/yao/orin/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu)
set(CMAKE_C_COMPILER ${tools}/bin/${TARGET_ARCHITECTURE}-gcc)
set(CMAKE_CXX_COMPILER ${tools}/bin/${TARGET_ARCHITECTURE}-g++)

# Define additional compiler flags
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -isystem=${TARGET_SYSROOT}/usr/include -isystem=${TARGET_SYSROOT}/usr/local/include -isystem=${TARGET_SYSROOT}/usr/include/${TARGET_ARCHITECTURE}")
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS}")

# Configure CMake find root path modes
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Set the install RPATH use and build RPATH
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
set(CMAKE_BUILD_RPATH ${TARGET_SYSROOT})

# Append to CMake library and prefix paths
list(APPEND CMAKE_LIBRARY_PATH ${CMAKE_SYSROOT}/usr/lib/${TARGET_ARCHITECTURE})
list(APPEND CMAKE_PREFIX_PATH "${CMAKE_SYSROOT}/usr/lib/${TARGET_ARCHITECTURE}/cmake")


CMakeLists.txt------------------------------------------------------------------------------

cmake_minimum_required(VERSION 3.10)
project(yolov5-tensorrt VERSION 0.1 DESCRIPTION "Real-time object detection with YOLOv5 and TensorRT")

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2 -g -Wall -Wextra -Wno-deprecated -fPIC")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -g -pthread")

set(CMAKE_INCLUDE_CURRENT_DIR ON)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
if(NOT DEFINED CMAKE_LIBRARY_OUTPUT_DIRECTORY)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
endif()


find_package(OpenCV REQUIRED)
# find_package(CUDA REQUIRED)

include_directories(include)

file(GLOB SOURCES "src/*.cc")

add_executable(camera_detect 
    main_camera.cc
    ${SOURCES}
)

target_include_directories(camera_detect PUBLIC 
    ${OpenCV_INCLUDE_DIRS} 
    ${CUDA_INCLUDE_DIR}
)

target_link_libraries(camera_detect 
    nvinfer
    nvonnxparser
    ${CUDA_LIB_DIR}
    ${OpenCV_LIBRARIES}
)

**Comment by PhysicsX** [comment]
This is not a Qt compilation, it is something else, I can not help for this.
