### ISSUE TITLE
Raspimage generation issue

### ISSUE THREAD

**Issue by carpajr** [PhysicsX/QTonRaspberryPi#20]
Hello!

Firstly, kudos to Ulas! I was very surprised when I found this project. This simplifies a lot cross-compiling letting the host intact practically.

This is just an observation that should affect the latest version of docker.

After run 
`docker buildx build --platform linux/arm64 -f DockerFileRasp -t raspimage .`

Resulting in:
```
[+] Building 1.5s (8/8) FINISHED                                                                   docker-container:mybuilder
 => [internal] load build definition from DockerFileRasp                                                                 0.0s
 => => transferring dockerfile: 2.58kB                                                                                   0.0s
 => WARN: FromPlatformFlagConstDisallowed: FROM --platform flag should not use constant value "linux/arm64" (line 4)     0.0s
 => [internal] load metadata for docker.io/arm64v8/debian:bookworm                                                       1.2s
 => [internal] load .dockerignore                                                                                        0.0s
 => => transferring context: 2B                                                                                          0.0s
 => [1/5] FROM docker.io/arm64v8/debian:bookworm@sha256:4466c6813e1d9a85fbac707afe419e13ce9a823f7041316bab860d8c0a50f91  0.1s
 => => resolve docker.io/arm64v8/debian:bookworm@sha256:4466c6813e1d9a85fbac707afe419e13ce9a823f7041316bab860d8c0a50f91  0.1s
 => CACHED [2/5] RUN touch /build.log                                                                                    0.0s
 => CACHED [3/5] RUN {     echo "deb http://deb.debian.org/debian bookworm main contrib non-free" > /etc/apt/sources.li  0.0s
 => CACHED [4/5] WORKDIR /build                                                                                          0.0s
 => CACHED [5/5] RUN tar cvfz rasp.tar.gz -C / lib usr/include usr/lib                                                   0.0s
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load

```
As a result, the docker image was not generated. 

To handle this, just add  `--output`.

`docker buildx build --output type=docker --platform linux/arm64 -f DockerFileRasp -t raspimage .`

**Comment by PhysicsX** [comment]
Hello,

Thanks for the comment and update :)

May I ask which version of docker are you using ?

I am going to try and update the page accordingly.

**Comment by carpajr** [comment]
For sure.

Docker version 27.3.1, build ce12230

I also have noted that QT 6.6.x is only available in archives. I have successfully compiled with QT 7.6.4, but I have not yet tested it.

**Comment by PhysicsX** [comment]
Yes I am going to update QT versions as well, But I dont see the error you saw for output. (with same docker version) I think problem is platform selection in the dockerfile itself, I am going to update it too. Instead of the command I will update the dockerfileRasp
