### ISSUE TITLE
Configure amd64 to arm64 build environment

### ISSUE THREAD

**Issue by HaonPAPA** [PhysicsX/QTonRaspberryPi#3]
I really enjoyed your video of qt cross-compiling on Raspberry 4!
The environment you created is a little different, but I have Ubuntu OS installed on the Raspberry 4 board, and the source development PC OS is also using ubuntu.
However, the architecture is different, so it seems that cross-compilation is required.
my development pc is amd64 and raspberry is arm64 can you tell me how to cross compile? Are you thinking of creating content?

**Comment by PhysicsX** [comment]
Hi,

The process should be same. Just remove the raspberry pi related commands. And you need to check related package versions. Probably some of them can be different. 
You can share your commands or history and other people can take advantage.
