### ISSUE TITLE
missing open SSL and cmake instructiosn

### ISSUE THREAD

**Issue by vj4sothername** [PhysicsX/QTonRaspberryPi#4]
hello, just working through this guide and ran into issues with the cmake portion. 

used the below to install cmake as it said i didn't have it already and didnt understand the git clone bit (total noob)

wget https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2.tar.gz
tar xf cmake-3.22.2.tar.gz
mkdir cbuild && cd cbuild
../cmake-3.22.2/bootstrap --prefix=/opt/cmake --parallel=4 && make -j4 && make install

from [https://www.tal.org/tutorials/building-qt-62-raspberry-pi](https://www.tal.org/tutorials/building-qt-62-raspberry-pi)

this failed as I was missing openssh so ran

sudo apt install libssl-dev

this then fixed the issue and cmake installed

I have basically no idea what I am doing so if this is wrong Im sorry, just trying to get it all working so I can struggle bus my way through creating a simple qt application that will take me 6 months when it should take an afternoon.

**Comment by PhysicsX** [comment]
Hello, Yes you are right. I will update the page about it.  There can be small wrog order of commands. but I will update them all. If you have a time, I will create also video content about it in a week or more.

Please continue to test the commands. If you find any important problem please let me know.

Thanks for info.
