### ISSUE TITLE
your user name & Qt creator

### ISSUE THREAD

**Issue by vj4sothername** [PhysicsX/QTonRaspberryPi#5]
In a few places you have your user name 

"cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DINPUT_opengl=es2 -DQT_BUILD_EXAMPLES=OFF -DQT_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/home/ulas/qt6Host"

unfortunatly, this isnt seen onscreen and easily missed. might be worth making it something that can fail so its easy to figure out for us laymans.

Also, if i want to use QT creator to program, do i need to do anything special to install it after following your guide?

**Comment by PhysicsX** [comment]
yes you should update the paths. Please read the commands carefully. I can add more comment about it. Qt6 is working with cmake anymore. So you can run it with any ide. For qtcreator you should congifure the device. Not much thing. You can run it also vscode.
