### ISSUE TITLE
Issue compiling QT

### ISSUE THREAD

**Issue by adrien-jaquiery** [PhysicsX/QTonRaspberryPi#6]
I came across an  error when executing the following command:

cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DQT_FEATURE_eglfs_egldevice=ON -DQT_FEATURE_eglfs_gbm=ON \
-DQT_BUILD_TOOLS_WHEN_CROSSCOMPILING=ON  -DQT_BUILD_EXAMPLES=OFF -DQT_BUILD_TESTS=OFF \
-DQT_HOST_PATH=/home/ulas/qt6Host -DCMAKE_STAGING_PREFIX=/home/ulas/qt6rpi \
-DCMAKE_INSTALL_PREFIX=/home/ulas/qt6crosspi -DCMAKE_PREFIX_PATH=/home/ulas/rpi-sdk/sysroot/usr/lib/ \
-DCMAKE_TOOLCHAIN_FILE=/home/ulas/qt-cross/toolchain.cmake /home/ulas/qt-cross/qtbase-everywhere-src-6.3.0/

Of course i changed the username. 

The error is the following:

ERROR: The OpenGL functionality tests failed!  You might need to modify the include and library search paths by editing QMAKE_INCDIR_OPENGL[_ES2], QMAKE_LIBDIR_OPENGL[_ES2] and QMAKE_LIBS_OPENGL[_ES2] in the mkspec for your platform.

CMake Error at cmake/QtBuildInformation.cmake:92 (message):
  Check the configuration messages for an error that has occurred.
Call Stack (most recent call first):
  cmake/QtBuildInformation.cmake:11 (qt_configure_print_summary)
  cmake/QtBuildInternals/QtBuildInternalsConfig.cmake:489 (qt_print_feature_summary)
  CMakeLists.txt:193 (qt_build_repo_end)

I am quite new to Linux and have no idea how to fix this. Could you help me ?
I added the output and the error log files. Thanks !

[CMakeOutput.log](https://github.com/PhysicsX/QTonRaspberryPi/files/8645820/CMakeOutput.log)
[CMakeError.log](https://github.com/PhysicsX/QTonRaspberryPi/files/8645821/CMakeError.log)

**Comment by PhysicsX** [comment]
Hello Adrien,
Did you update the sysroot correctly ? I saw this command when I enabled the es2. But in your case you did not enable it. Could you please share the history also ? I see also here fatal error: cannot find 'ld' in your log file. That can be means that you did not have good sysroot.

**Comment by adrien-jaquiery** [comment]
Hello,

I initially started from  Raspbian lite with manually installed desktop but I then started everything again with the 32bits desktop version of Raspbian and then everything works as it should.

Thanks you very much.
