### ISSUE TITLE
Missing Pi LIBs

### ISSUE THREAD

**Issue by vj4sothername** [PhysicsX/QTonRaspberryPi#7]
Hello, 

I get the below when setting up the Pi:

Unable to locate package libboost1.71-all-dev

E: Couldn't find any package by glob 'libboost1.71-all-dev'

E: Couldn't find any package by regex 'libboost1.71-all-dev'

E: Unable to locate package libsrtp0-dev

and in the second batch

E: Unable to locate package libsqlite0-dev

Thanks for the work and vid on this :-)

**Comment by vj4sothername** [comment]
libboost1.74-all-dev will install. Trying to find a fix for the others. ATM

**Comment by vj4sothername** [comment]
they where installed with apt-get having used apt cache search to find them. is it not simply the latest versions? 

If this is a case of the latest pi version you may need to specify what version you are running as I simply followed the update steps.

I am facing issues with the Compile the Qt6.3.0 stage after running  

"ERROR: The OpenGL functionality tests failed!  You might need to modify the include and library search paths by editing QMAKE_INCDIR_OPENGL[_ES2], QMAKE_LIBDIR_OPENGL[_ES2] and QMAKE_LIBS_OPENGL[_ES2] in the mkspec for your platform.
"

I'll wipe everything and start again.

**Comment by vj4sothername** [comment]
Pi 4, maybe i had the 64bit os it was built the other month and i forgot... Started from scratch, new pi build matching everything you said including the firmware. Fresh ubuntu install 22.04 build and now its stuck at the compiler.

`- The CXX compiler identification is GNU 8.3.0
-- The C compiler identification is GNU 8.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /opt/rpi/rpi-gcc-8.3.0/bin/arm-linux-gnueabihf-gcc
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /opt/rpi/rpi-gcc-8.3.0/bin/arm-linux-gnueabihf-g++
-- Check for working CXX compiler: /opt/rpi/rpi-gcc-8.3.0/bin/arm-linux-gnueabihf-g++ - broken
CMake Error at /usr/local/share/cmake-3.23/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/opt/rpi/rpi-gcc-8.3.0/bin/arm-linux-gnueabihf-g++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/ulas/qt-cross/CMakeFiles/CMakeTmp`

**Comment by PhysicsX** [comment]
I think you missed some steps. Could you please share the os version 
output of lsb-release or another command.
Also history. Lets check.

**Comment by vj4sothername** [comment]
Just started again..... exactly the same build, using the same file.

las@ulas:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy


ulas@ulas:~$ uname -a
Linux ulas 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Had to sudo mkdir /opt/rpi 

its got further but still no config.

ulas@ulas:~/qt-cross$ cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DQT_FEATURE_eglfs_egldevice=ON -DQT_FEATURE_eglfs_gbm=ON \
-DQT_BUILD_TOOLS_WHEN_CROSSCOMPILING=ON  -DQT_BUILD_EXAMPLES=OFF -DQT_BUILD_TESTS=OFF \
-DQT_HOST_PATH=/home/ulas/qt6Host -DCMAKE_STAGING_PREFIX=/home/ulas/qt6rpi \
-DCMAKE_INSTALL_PREFIX=/home/ulas/qt6crosspi -DCMAKE_PREFIX_PATH=/home/ulas/rpi-sdk/sysroot/usr/lib/ \
-DCMAKE_TOOLCHAIN_FILE=/home/ulas/qt-cross/toolchain.cmake /home/ulas/qt-cross/qtbase-everywhere-src-6.3.0/
-- The CXX compiler identification is GNU 8.3.0
-- The C compiler identification is GNU 8.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /opt/rpi/rpi-gcc-8.3.0/bin/arm-linux-gnueabihf-gcc
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rpi/rpi-gcc-8.3.0/bin/arm-linux-gnueabihf-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rpi/rpi-gcc-8.3.0/bin/arm-linux-gnueabihf-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find double-conversion (missing: double-conversion_DIR)
-- Could NOT find md4c (missing: md4c_DIR)
CMake Warning (dev) at cmake/3rdparty/extra-cmake-modules/find-modules/FindXCB.cmake:180 (message):
  XINPUT from XCB was requested: this is EXPERIMENTAL and is likely to
  unavailable on many systems!
Call Stack (most recent call first):
  cmake/QtFindPackageHelpers.cmake:130 (find_package)
  src/gui/configure.cmake:119 (qt_find_package)
  cmake/QtFeature.cmake:573 (include)
  src/CMakeLists.txt:12 (qt_feature_evaluate_features)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find double-conversion (missing: double-conversion_DIR)
-- Could NOT find md4c (missing: md4c_DIR)
CMake Warning (dev) at cmake/3rdparty/extra-cmake-modules/find-modules/FindXCB.cmake:180 (message):
  XINPUT from XCB was requested: this is EXPERIMENTAL and is likely to
  unavailable on many systems!
Call Stack (most recent call first):
  cmake/QtFindPackageHelpers.cmake:130 (find_package)
  src/gui/configure.cmake:119 (qt_find_package)
  cmake/QtModuleHelpers.cmake:570 (include)
  src/gui/CMakeLists.txt:53 (qt_internal_add_module)
This warning is for project developers.  Use -Wno-dev to suppress it.


-- Configuring done
-- Generating done
-- Build files have been written to: /home/ulas/qt-cross


history:
    1  ~/qtCrossExample$ lsb_release -a
    2  lsb_release -a
    3  uname -a
    4  sudo apt-get update
    5  sudo apt-get upgrade
    6  sudo apt-get install make build-essential libclang-dev ninja-build gcc git bison python3 gperf pkg-config libfontconfig1-dev libfreetype6-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-util-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libatspi2.0-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev
    7  sudo apt install libssl-dev
    8  git clone https://github.com/Kitware/CMake.git
    9  cd CMake
   10  ./bootstrap && make && sudo make install
   11  cd ~
   12  wget https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qtbase-everywhere-src-6.3.0.tar.xz
   13  mkdir qt6HostBuild
   14  cd qt6HostBuild
   15  ar xf ../qtbase-everywhere-src-6.3.0.tar.xz
   16  tar xf ../qtbase-everywhere-src-6.3.0.tar.xz
   17  cd qtbase-everywhere-src-6.3.0
   18  cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DINPUT_opengl=es2 -DQT_BUILD_EXAMPLES=OFF -DQT_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/home/ulas/qt6Host
   19  cmake --build . --parallel 2
   20  cmake --install .
   21  cd $home
   22  mkdir /opt/rpi
   23  sudo mkdir /opt/rpi
   24  sudo wget www.ulasdikme.com/yedek/rpi-gcc-8.3.0_linux.tar.xz
   25  cd /opt/rpi
   26  sudo wget www.ulasdikme.com/yedek/rpi-gcc-8.3.0_linux.tar.xz
   27  tar xf rpi-gcc-8.3.0_linux.tar.xz 
   28  sudo tar xf rpi-gcc-8.3.0_linux.tar.xz 
   29  ls -l | grep rpi-gcc-8.3.0
   30  cd $HOME
   31  mkdir rpi-sdk
   32  cd rpi-sdk
   33  mkdir sysroot sysroot/usr sysroot/opt
   34  rsync -avz --rsync-path="sudo rsync" pi@192.168.0.207:/usr/include sysroot/usr
   35  rsync -avz --rsync-path="sudo rsync" pi@192.168.0.207:/lib sysroot
   36  rsync -avz --rsync-path="sudo rsync" pi@192.168.0.207:/usr/lib sysroot/usr
   37  rsync -avz --rsync-path="sudo rsync" pi@192.168.0.207:/opt/vc sysroot/opt
   38  wget https://raw.githubusercontent.com/riscv/riscv-poky/master/scripts/sysroot-relativelinks.py
   39  chmod +x sysroot-relativelinks.py 
   40  python3 sysroot-relativelinks.py sysroot
   41  cd ..
   42  mkdir qt-cross
   43  cd qt-cross
   44  sudo nano toolchain.cmake
   45  ls
   46  tar xf ../qtbase-everywhere-src-6.3.0.tar.xz
   47  cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DQT_FEATURE_eglfs_egldevice=ON -DQT_FEATURE_eglfs_gbm=ON -DQT_BUILD_TOOLS_WHEN_CROSSCOMPILING=ON  -DQT_BUILD_EXAMPLES=OFF -DQT_BUILD_TESTS=OFF -DQT_HOST_PATH=/home/ulas/qt6Host -DCMAKE_STAGING_PREFIX=/home/ulas/qt6rpi -DCMAKE_INSTALL_PREFIX=/home/ulas/qt6crosspi -DCMAKE_PREFIX_PATH=/home/ulas/rpi-sdk/sysroot/usr/lib/ -DCMAKE_TOOLCHAIN_FILE=/home/ulas/qt-cross/toolchain.cmake /home/ulas/qt-cross/qtbase-everywhere-src-6.3.0/

**Comment by PhysicsX** [comment]
Config is in the file. check the directory. I explain this in the video.

**Comment by vj4sothername** [comment]
you are correct i apologise. i think trying to get this working has fried my brain. HelloQt6 example is working but qtGui isn't 

pi@raspberrypi:~ $ ./qtGui
./qtGui: error while loading shared libraries: libQt6Widgets.so.6: cannot open shared object file: No such file or directory

i can see the file in qt6rpi/lib on the host pc

**Comment by vj4sothername** [comment]
Trying to install the modules and cant get qtdocs to install. Will you be doing follow up guides/vids on this?

**Comment by PhysicsX** [comment]
So as I understand you did the compilation successfully for qtbase6. I am going to clsoe this ticket.

Yes I did module compilation and in the following days I will publish from here as a second part. :)
