### ISSUE TITLE
Cross compiling getting error gnu/stubs-32.h: No such file or directory

### ISSUE THREAD

**Issue by Rhvarrier** [PhysicsX/QTonRaspberryPi#8]
While trying to cross compile raspberry pi I'm getting the following error message
`In file included from /home/Raspi/qt6_build/sysroot/usr/include/features.h:485,
                 from /home/Raspi/CrossCompiler/cross-pi-gcc-10.2.0-0/arm-linux-gnueabihf/include/c++/10.2.0/arm-linux-gnueabihf/bits/os_defines.h:39,
                 from /home/Raspi/CrossCompiler/cross-pi-gcc-10.2.0-0/arm-linux-gnueabihf/include/c++/10.2.0/arm-linux-gnueabihf/bits/c++config.h:518,
                 from /home/Raspi/CrossCompiler/cross-pi-gcc-10.2.0-0/arm-linux-gnueabihf/include/c++/10.2.0/bits/stl_algobase.h:59,
                 from /home/Raspi/CrossCompiler/cross-pi-gcc-10.2.0-0/arm-linux-gnueabihf/include/c++/10.2.0/memory:63,
                 from /home/Raspi/qt6_build/qt/build/src/plugins/platformthemes/gtk3/QGtk3ThemePlugin_autogen/EWIEGA46WW/moc_qgtk3dialoghelpers.cpp:9,
                 from /home/Raspi/qt6_build/qt/build/src/plugins/platformthemes/gtk3/QGtk3ThemePlugin_autogen/mocs_compilation.cpp:2:
/usr/include/x86_64-linux-gnu/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file or directory
    7 | # include <gnu/stubs-32.h>
`
I don't understand why cmake is searching for include files in usr/include/x86_64-linux-gnu/gnu/ even though the cross compiler seems to be configured correctly

**Comment by PhysicsX** [comment]
Probably because of different version of OS? Could you please share history and OS version for raspberry pi.

**Comment by Rhvarrier** [comment]
After further investigation it seems that the following line are missing in the CMake Toolchain file provided:
`set(ENV{PKG_CONFIG_PATH} "")
set(ENV{PKG_CONFIG_LIBDIR} ${CMAKE_SYSROOT}/usr/lib/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig)
set(ENV{PKG_CONFIG_SYSROOT_DIR} ${CMAKE_SYSROOT})`

After adding these line the issue was resolved

**Comment by PhysicsX** [comment]
Are you using different toolchain? I did not see this issue?

**Comment by Rhvarrier** [comment]
Yes I'm using gcc-10.2 for armv6

**Comment by PhysicsX** [comment]
Nice. That is why you see this issues. Are you able to compile it successfully ? If it is so, could you please share the exact link of the toolchain ? And is there any additional steps that you have done ? I have not tried it with default toolchain, I can try and add to the page for other people.

thanks.
