### ISSUE TITLE
Error test with gui

### ISSUE THREAD

**Issue by kang2k10** [PhysicsX/QTonRaspberryPi#9]
After compilling. I create qtGui. compiling and copy to RPI
but run ./qtGui with error
`./qtGui: error while loading shared libraries: libQt6Widgets.so.6: cannot open shared object file: No such file or directory
`
ldd qtGui
`        libQt6Widgets.so.6 => not found
        libQt6Gui.so.6 => not found
`
file in
/usr/local/qt6rpi/lib/libQt6Widgets.so.6
/usr/local/qt6rpi/lib/libQt6Gui.so.6

How fix this ?

**Comment by kang2k10** [comment]
Ok. i remove all. and again cross compiling step by step. After test, i write about

**Comment by kang2k10** [comment]
echo $LD_LIBRARYPATH is blank
by env
LD_LIBRARY_PATH=:/usr/local/qt6rpi/lib/

**Comment by PhysicsX** [comment]
Is there any update from this issue?
